### ISSUE TITLE
Install issues and vulnerabilities

### ISSUE THREAD

**Issue by philsherry** [tanem/archiver-webpack-plugin#447]
Install command resolved silently, but nothing actually installed. I ran the command again with `--verbose` and saw that it was expecting `webpack ^4.x` (I'm running 5.x), despite the only up-front warning being about `node 10` or higher. 

Out of interest, I ran the install command again, with `--force` this time. 

`46 vulnerabilities (5 low, 6 moderate, 35 high)`

The project was previously at zero, so this wasn't thrilling. I ran `npm audit fix` twice and it ended up here:

`59 vulnerabilities (31 low, 2 moderate, 26 high)`

So, aside from letting people know about the reliance on Webpack 5, you'll want to be fixing those vulnerabilities as well. 

Hope that helps in some way.

**Comment by tanem** [comment]
Thanks, I'll add a comment about webpack 4 to the README now.

Re the vulnerabilities, Dependabot isn't giving me any security alerts for this library, and when I run `audit` with npm v7.12.0 I only see `4 vulnerabilities (3 moderate, 1 high).  I'll fix those now too.
